### ISSUE TITLE
Decorator Error

### ISSUE THREAD

**Issue by radyas** [indietyp/django-automated-logging#11]
Unable to use Admin site when decorator is added 

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/d_drive/Projects/Avantrio/Projects/venv/amat/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/d_drive/Projects/Avantrio/Projects/venv/amat/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/d_drive/Projects/Avantrio/Projects/venv/amat/lib/python3.8/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/d_drive/Projects/Avantrio/Projects/venv/amat/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/d_drive/Projects/Avantrio/Projects/venv/amat/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/d_drive/Projects/Avantrio/Projects/venv/amat/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/d_drive/Projects/Avantrio/Projects/venv/amat/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/d_drive/Projects/Avantrio/Projects/venv/amat/lib/python3.8/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/d_drive/Projects/Avantrio/Projects/venv/amat/lib/python3.8/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/d_drive/Projects/Avantrio/Projects/venv/amat/lib/python3.8/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/d_drive/Projects/Avantrio/Projects/advantis-amat/backend/apps/users/admin.py", line 5, in <module>
    admin.site.register(User, UserAdmin)
  File "/d_drive/Projects/Avantrio/Projects/venv/amat/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 106, in register
    for model in model_or_iterable:
TypeError: 'function' object is not iterable

**Comment by indietyp** [comment]
thank you for the error report, trying to reproduce the issue and fix it
